### ISSUE TITLE
Limit memory usage

### ISSUE THREAD

**Issue by benjaminpick** [webgriffe/docker-php-apache-base#2]
One thing I've run into (that you might fix as well): as memory_limit was infinite, this image filled my whole RAM when I executed a specific request. This is really bad because as soon as it is full, my linux graphic environment starts to become unusable, so I couldn't even kill it fast enough.

Only after limiting the memory usage:
https://github.com/benjaminpick/docker-php-apache-base/commit/51e3c064f6f1e86d4891caf0d0b11fb694373409
I found the culprit (a recursive var_dump which somehow produced an output of infinite length). 

I have also learned that the docker-compose.yml can also contain memory limits:

``` yml
server:
  mem_limit: 301m
  image: webgriffe/docker-php-apache-base
...
```
